apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: dev
  labels:
    app: appointment-service
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: mahesh541/api-appointment-service:latest
          ports:
            - containerPort: 2346
          env: # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: mylogo-config
                  key: host

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: mylogo-config
                  key: dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: mylogo-secrets
                  key: username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: mylogo-secrets
                  key: password
            - name: INSTANCE_CONNECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: mylogo-secrets
                  key: instanceName

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: appointment-service
  namespace: dev
spec:
  selector:
    app: appointment-service
  ports:
    - protocol: TCP
      port: 80 # The port that the service is running on in the cluster
      targetPort: 2346 # The port exposed by the service
  type: LoadBalancer # type of the service.
